apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: default
  labels:
    app: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: mkamel/webapp:latest
        ports:
        - containerPort: 8080
        env:
        - name: TREE
          value: "Oak"
        resources:
          requests:
            memory: "265Mi"
            cpu: "1"
          limits:
            memory: "512Mi"
            cpu: "2"
--- 
apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: "local.ecosia.org"
    http:
      paths:
      - path: "/tree"
        pathType: Prefix
        backend:
          service:
            name: webapp
            port:
              number: 80
